version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: readitlater-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME:-readitlater}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - readitlater-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: readitlater-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - readitlater-network
    command: redis-server --appendonly yes

  # Golang Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: readitlater-backend-dev
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-readitlater}?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - LOCAL_STORAGE_PATH=/app/data/storage
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - DEBUG=true
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - ./backend:/app
      - ./data/storage:/app/data/storage
      - ./logs:/app/logs
      - go_mod_cache:/go/pkg/mod
    networks:
      - readitlater-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    command: air -c .air.toml

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: readitlater-frontend-dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${BACKEND_URL:-http://localhost:8080}
      - VITE_APP_NAME=Read-It-Later
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./data/storage:/app/public/storage
    networks:
      - readitlater-network
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

  # Nginx for development proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: readitlater-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - readitlater-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  go_mod_cache:
    driver: local

networks:
  readitlater-network:
    driver: bridge 